"""add phase3 notification delivery

Revision ID: 3bed66d88cf4
Revises: f6b2c4d8e901
Create Date: 2026-08-08 06:52:41.502887
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "3bed66d88cf4"
down_revision: Union[str, Sequence[str], None] = "f6b2c4d8e901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_events_idempotency_key"),
    )
    op.create_index(
        "ix_outbox_events_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_events_status_created", "outbox_events", ["status", "created_at"], unique=False
    )
    op.create_table(
        "notification_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "auth_type",
            sa.Enum(
                "NONE",
                "BEARER",
                "HEADER",
                name="notification_auth_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("auth_header_name", sa.String(length=128), nullable=True),
        sa.Column("secret_reference", sa.String(length=128), nullable=True),
        sa.Column("ticket_created_template", sa.Text(), nullable=False),
        sa.Column("ticket_replied_template", sa.Text(), nullable=False),
        sa.Column("success_status_codes", sa.JSON(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_base_seconds", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["accounts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_notification_configurations_name"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("outbox_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ticket_created",
                "ticket_replied",
                name="notification_event_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_address", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "DELIVERING",
                "RETRY_SCHEDULED",
                "DELIVERED",
                "PERMANENT_FAILURE",
                "SKIPPED",
                name="notification_delivery_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=320), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("cycle_attempt", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.String(length=500), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("response_summary", sa.String(length=500), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["outbox_id"], ["outbox_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_notification_deliveries_idempotency_key"),
    )
    op.create_index(
        "ix_notification_deliveries_event_created",
        "notification_deliveries",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_outbox", "notification_deliveries", ["outbox_id"], unique=False
    )
    op.create_index(
        "ix_notification_deliveries_status_next",
        "notification_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_deliveries_status_next", table_name="notification_deliveries")
    op.drop_index("ix_notification_deliveries_outbox", table_name="notification_deliveries")
    op.drop_index("ix_notification_deliveries_event_created", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("notification_configurations")
    op.drop_index("ix_outbox_events_status_created", table_name="outbox_events")
    op.drop_index("ix_outbox_events_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
