"""create document ingestion tables

Revision ID: d1a97d2e451b
Revises: baaf88cba66a
Create Date: 2026-08-02 17:26:58.394878
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "d1a97d2e451b"
down_revision: Union[str, Sequence[str], None] = "baaf88cba66a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["system_id"], ["business_systems.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_system_updated", "documents", ["system_id", "updated_at"], unique=False
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PARSING",
                "CHUNKING",
                "CHUNKED",
                "READY_DRAFT",
                "OCR_REQUIRED",
                "FAILED",
                name="document_version_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("chunk_manifest_key", sa.String(length=1024), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("parser_name", sa.String(length=100), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("schema_version", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_no", name="uq_document_versions_number"),
        sa.UniqueConstraint("object_key", name="uq_document_versions_object_key"),
    )
    op.create_index(
        "ix_document_versions_status_updated",
        "document_versions",
        ["status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("system_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "RETRY_SCHEDULED",
                "SUCCEEDED",
                "FAILED",
                name="ingestion_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "STORED",
                "PARSING",
                "CHUNKING",
                "COMPLETED",
                name="ingestion_stage",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("last_dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("attempt >= 0", name="ck_ingestion_jobs_attempt"),
        sa.CheckConstraint("max_attempts > 0", name="ck_ingestion_jobs_max_attempts"),
        sa.CheckConstraint("progress >= 0 AND progress <= 100", name="ck_ingestion_jobs_progress"),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["system_id"], ["business_systems.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_id", name="uq_ingestion_jobs_document_version"),
        sa.UniqueConstraint(
            "actor_id",
            "system_id",
            "idempotency_key",
            name="uq_ingestion_jobs_idempotency_scope",
        ),
    )
    op.create_index(
        "ix_ingestion_jobs_dispatch",
        "ingestion_jobs",
        ["status", "next_retry_at", "last_dispatched_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_lease", "ingestion_jobs", ["status", "lease_expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingestion_jobs_lease", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_dispatch", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index("ix_document_versions_status_updated", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index("ix_documents_system_updated", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
